/* Atlas - the systemd user service unit.
 * Copyright 2026 The Atlas Authors. Licensed under the Apache License 2.0.
 */
#define _GNU_SOURCE 1

#include "atlas/unit.h"

#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "atlas/atlas.h"

/* Written into the unit and checked before Atlas overwrites or removes one.
 * It is how "a unit Atlas generated" is distinguished from "a unit somebody
 * wrote", which is the difference between a safe overwrite and data loss. */
#define ATLAS_UNIT_MARKER "# Generated by atlas service install. Safe for Atlas to replace."

void atlas_unit_install_report_init(atlas_unit_install_report *r) {
    memset(r, 0, sizeof(*r));
    atlas_buf_init(&r->path);
    atlas_buf_init(&r->dir);
    atlas_buf_init(&r->unit_text);
}

void atlas_unit_install_report_free(atlas_unit_install_report *r) {
    if (r == NULL) {
        return;
    }
    atlas_buf_free(&r->path);
    atlas_buf_free(&r->dir);
    atlas_buf_free(&r->unit_text);
}

/* --- paths --------------------------------------------------------------- */

atlas_status atlas_unit_self_path(atlas_buf *out, atlas_err *err) {
    atlas_buf_reset(out);
    char buf[4096];
    ssize_t n = readlink("/proc/self/exe", buf, sizeof(buf) - 1u);
    if (n <= 0) {
        return atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno,
                                   "cannot determine this executable's path from /proc/self/exe");
    }
    buf[n] = '\0';
    if (buf[0] != '/') {
        return atlas_err_set(err, ATLAS_ERR_CONFIG,
                             "this executable's path is not absolute; refusing to write a unit");
    }
    return atlas_buf_set(out, buf, (size_t)n, err);
}

atlas_status atlas_unit_dir(atlas_buf *out, atlas_err *err) {
    atlas_buf_reset(out);
    const char *cfg = getenv("XDG_CONFIG_HOME");
    if (cfg != NULL && cfg[0] != '\0') {
        if (cfg[0] != '/') {
            return atlas_err_set(err, ATLAS_ERR_CONFIG,
                                 "XDG_CONFIG_HOME must be an absolute path, got \"%s\"", cfg);
        }
        size_t n = strlen(cfg);
        while (n > 1u && cfg[n - 1u] == '/') {
            n--;
        }
        atlas_status st = atlas_buf_append(out, cfg, n, err);
        if (st != ATLAS_OK) {
            return st;
        }
    } else {
        const char *home = getenv("HOME");
        if (home == NULL || home[0] != '/') {
            return atlas_err_set(err, ATLAS_ERR_CONFIG,
                                 "neither XDG_CONFIG_HOME nor an absolute HOME is set, so there is "
                                 "no user unit directory to write to");
        }
        size_t n = strlen(home);
        while (n > 1u && home[n - 1u] == '/') {
            n--;
        }
        atlas_status st = atlas_buf_append(out, home, n, err);
        if (st == ATLAS_OK) {
            st = atlas_buf_append_str(out, "/.config", err);
        }
        if (st != ATLAS_OK) {
            return st;
        }
    }
    return atlas_buf_append_str(out, "/systemd/user", err);
}

atlas_status atlas_unit_path(atlas_buf *out, atlas_err *err) {
    atlas_status st = atlas_unit_dir(out, err);
    if (st == ATLAS_OK) {
        st = atlas_buf_append_str(out, "/" ATLAS_UNIT_FILENAME, err);
    }
    return st;
}

/* --- rendering ----------------------------------------------------------- */

/* A unit file is executed. Rather than work out systemd's quoting rules for an
 * arbitrary path and hope, Atlas refuses any path that would need them. Every
 * realistic installation prefix passes; a path that does not is a clear message
 * instead of a mis-quoted ExecStart. */
static atlas_status check_unit_safe_path(const char *p, const char *what, atlas_err *err) {
    if (p == NULL || p[0] != '/') {
        return atlas_err_set(err, ATLAS_ERR_CONFIG, "%s must be an absolute path", what);
    }
    for (const unsigned char *q = (const unsigned char *)p; *q != '\0'; q++) {
        if (*q < 0x21u || *q > 0x7eu || *q == '"' || *q == '\'' || *q == '\\' || *q == '%' ||
            *q == '$' || *q == ';') {
            return atlas_err_set(err, ATLAS_ERR_CONFIG,
                                 "%s contains a character Atlas will not place in a systemd unit "
                                 "unquoted (byte 0x%02x). Install Atlas somewhere with a plain "
                                 "path, or write the unit by hand from `atlas service print`.",
                                 what, (unsigned)*q);
        }
    }
    return ATLAS_OK;
}

atlas_status atlas_unit_render(const char *exe_path, const char *data_dir_override, atlas_buf *out,
                               atlas_err *err) {
    atlas_status st = check_unit_safe_path(exe_path, "the Atlas executable path", err);
    if (st != ATLAS_OK) {
        return st;
    }
    if (data_dir_override != NULL && data_dir_override[0] != '\0') {
        st = check_unit_safe_path(data_dir_override, "the data directory", err);
        if (st != ATLAS_OK) {
            return st;
        }
    }

    atlas_buf_reset(out);
    return atlas_buf_appendf(
        out, err,
        ATLAS_UNIT_MARKER "\n"
        "# atlas %s\n"
        "\n"
        "[Unit]\n"
        "Description=Atlas repository index daemon\n"
        "Documentation=man:atlas(1)\n"
        "# The daemon needs a writable data directory and a private runtime\n"
        "# directory; both belong to the user session, not to the system.\n"
        "After=default.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        "# Foreground. systemd owns supervision, restart and log capture; a\n"
        "# service that forks into the background hides its own failures.\n"
        "ExecStart=%s daemon run%s%s\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "# Files Atlas creates describe private repositories.\n"
        "UMask=0077\n"
        "# $XDG_RUNTIME_DIR/atlas, created 0700 by systemd and removed on stop.\n"
        "RuntimeDirectory=atlas\n"
        "RuntimeDirectoryMode=0700\n"
        "# Hardening. None of these is load-bearing for correctness — Atlas does\n"
        "# not need any of what they remove — so each one is free.\n"
        "NoNewPrivileges=yes\n"
        "PrivateTmp=yes\n"
        "ProtectSystem=strict\n"
        "ProtectHome=read-only\n"
        "ProtectKernelTunables=yes\n"
        "ProtectKernelModules=yes\n"
        "ProtectControlGroups=yes\n"
        "RestrictSUIDSGID=yes\n"
        "RestrictRealtime=yes\n"
        "MemoryDenyWriteExecute=yes\n"
        "LockPersonality=yes\n"
        "# Atlas performs no network access at all.\n"
        "PrivateNetwork=yes\n"
        "IPAddressDeny=any\n"
        "SystemCallArchitectures=native\n"
        "SystemCallFilter=@system-service\n"
        "SystemCallFilter=~@privileged @resources @obsolete\n"
        "# ProtectHome=read-only would block the index; the data directory is\n"
        "# the one place the daemon writes.\n"
        "ReadWritePaths=%%h/.local/share/atlas\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
        "\n"
        "# After installing:\n"
        "#   systemctl --user daemon-reload\n"
        "#   systemctl --user enable --now atlas\n"
        "# For the daemon to survive logging out of an SSH session, the user\n"
        "# needs lingering enabled. That requires root, once, and is the only\n"
        "# step in Atlas' setup that does:\n"
        "#   sudo loginctl enable-linger $USER\n",
        ATLAS_VERSION_STRING, exe_path,
        (data_dir_override != NULL && data_dir_override[0] != '\0') ? " --data-dir " : "",
        (data_dir_override != NULL && data_dir_override[0] != '\0') ? data_dir_override : "");
}

/* --- installation -------------------------------------------------------- */

static atlas_status ensure_dir(const char *dir, bool *created, atlas_err *err) {
    *created = false;
    /* Create each component, so a fresh account with no ~/.config still works. */
    size_t n = strlen(dir);
    atlas_buf partial = ATLAS_BUF_INIT;
    atlas_status st = ATLAS_OK;
    for (size_t i = 1; i <= n; i++) {
        if (i != n && dir[i] != '/') {
            continue;
        }
        atlas_buf_reset(&partial);
        st = atlas_buf_append(&partial, dir, i, err);
        if (st != ATLAS_OK) {
            break;
        }
        const char *p = atlas_buf_cstr(&partial);
        if (mkdir(p, S_IRWXU) != 0) {
            if (errno != EEXIST) {
                st = atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot create %s", p);
                break;
            }
        } else if (i == n) {
            *created = true;
        }
        struct stat sb;
        if (lstat(p, &sb) != 0) {
            st = atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot stat %s", p);
            break;
        }
        if (S_ISLNK(sb.st_mode)) {
            st = atlas_err_set(err, ATLAS_ERR_INTEGRITY,
                               "%s is a symbolic link; refusing to install a unit through it", p);
            break;
        }
        if (!S_ISDIR(sb.st_mode)) {
            st = atlas_err_set(err, ATLAS_ERR_INTEGRITY, "%s exists and is not a directory", p);
            break;
        }
    }
    atlas_buf_free(&partial);
    return st;
}

/* Reads an existing unit so that "Atlas wrote this" and "the content is already
 * correct" can both be decided before anything is overwritten. */
static atlas_status read_existing(const char *path, atlas_buf *out, bool *exists, atlas_err *err) {
    *exists = false;
    atlas_buf_reset(out);
    struct stat sb;
    if (lstat(path, &sb) != 0) {
        if (errno == ENOENT) {
            return ATLAS_OK;
        }
        return atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot inspect %s", path);
    }
    if (S_ISLNK(sb.st_mode)) {
        return atlas_err_set(err, ATLAS_ERR_INTEGRITY,
                             "%s is a symbolic link; refusing to write through it", path);
    }
    if (!S_ISREG(sb.st_mode)) {
        return atlas_err_set(err, ATLAS_ERR_INTEGRITY,
                             "%s exists and is not a regular file; refusing to replace it", path);
    }
    if (sb.st_size > 1024L * 1024L) {
        return atlas_err_set(err, ATLAS_ERR_INTEGRITY,
                             "%s is far larger than a unit file; refusing to replace it", path);
    }
    int fd = open(path, O_RDONLY | O_NOFOLLOW | O_CLOEXEC);
    if (fd < 0) {
        return atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot read %s", path);
    }
    *exists = true;
    char buf[8192];
    for (;;) {
        ssize_t r = read(fd, buf, sizeof(buf));
        if (r < 0) {
            if (errno == EINTR) {
                continue;
            }
            atlas_status st = atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot read %s",
                                                  path);
            (void)close(fd);
            return st;
        }
        if (r == 0) {
            break;
        }
        atlas_status st = atlas_buf_append(out, buf, (size_t)r, err);
        if (st != ATLAS_OK) {
            (void)close(fd);
            return st;
        }
    }
    (void)close(fd);
    return ATLAS_OK;
}

/* Atomic write: a temporary in the same directory, then rename.
 *
 * systemd may read the unit at any moment. A partially written unit would be a
 * unit systemd rejects, so the file is never observably incomplete. */
static atlas_status write_atomic(const char *path, const char *data, size_t len, atlas_err *err) {
    atlas_buf tmp = ATLAS_BUF_INIT;
    atlas_status st = atlas_buf_set_str(&tmp, path, err);
    if (st == ATLAS_OK) {
        st = atlas_buf_append_str(&tmp, ".atlas-new", err);
    }
    if (st != ATLAS_OK) {
        atlas_buf_free(&tmp);
        return st;
    }
    const char *tmp_path = atlas_buf_cstr(&tmp);
    (void)unlink(tmp_path);
    int fd = open(tmp_path, O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW | O_CLOEXEC,
                  S_IRUSR | S_IWUSR);
    if (fd < 0) {
        st = atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot create %s", tmp_path);
        atlas_buf_free(&tmp);
        return st;
    }
    size_t off = 0;
    while (off < len) {
        ssize_t wn = write(fd, data + off, len - off);
        if (wn < 0) {
            if (errno == EINTR) {
                continue;
            }
            st = atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot write %s", tmp_path);
            break;
        }
        off += (size_t)wn;
    }
    if (st == ATLAS_OK && fsync(fd) != 0) {
        st = atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot flush %s", tmp_path);
    }
    (void)close(fd);
    if (st == ATLAS_OK && rename(tmp_path, path) != 0) {
        st = atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot install %s", path);
    }
    if (st != ATLAS_OK) {
        (void)unlink(tmp_path);
    }
    atlas_buf_free(&tmp);
    return st;
}

atlas_status atlas_unit_install(const char *exe_path, const char *data_dir_override, bool force,
                                atlas_unit_install_report *out, atlas_err *err) {
    atlas_status st = atlas_unit_render(exe_path, data_dir_override, &out->unit_text, err);
    if (st == ATLAS_OK) {
        st = atlas_unit_dir(&out->dir, err);
    }
    if (st == ATLAS_OK) {
        st = atlas_unit_path(&out->path, err);
    }
    if (st != ATLAS_OK) {
        return st;
    }

    st = ensure_dir(atlas_buf_cstr(&out->dir), &out->created_dir, err);
    if (st != ATLAS_OK) {
        return st;
    }

    atlas_buf existing = ATLAS_BUF_INIT;
    bool exists = false;
    st = read_existing(atlas_buf_cstr(&out->path), &existing, &exists, err);
    if (st != ATLAS_OK) {
        atlas_buf_free(&existing);
        return st;
    }
    if (exists) {
        if (existing.len == out->unit_text.len &&
            memcmp(existing.data, out->unit_text.data, existing.len) == 0) {
            out->unchanged = true;
            atlas_buf_free(&existing);
            return ATLAS_OK;
        }
        bool ours = (strstr(atlas_buf_cstr(&existing), ATLAS_UNIT_MARKER) != NULL);
        if (!ours && !force) {
            atlas_buf_free(&existing);
            return atlas_err_set(err, ATLAS_ERR_INTEGRITY,
                                 "%s already exists and was not written by Atlas. Review it "
                                 "against `atlas service print`, then move it aside or pass "
                                 "--force to replace it.",
                                 atlas_buf_cstr(&out->path));
        }
        out->replaced_existing = true;
    }
    atlas_buf_free(&existing);

    st = write_atomic(atlas_buf_cstr(&out->path), out->unit_text.data, out->unit_text.len, err);
    if (st == ATLAS_OK) {
        out->wrote_file = true;
    }
    return st;
}

atlas_status atlas_unit_uninstall(bool force, atlas_unit_install_report *out, atlas_err *err) {
    atlas_status st = atlas_unit_dir(&out->dir, err);
    if (st == ATLAS_OK) {
        st = atlas_unit_path(&out->path, err);
    }
    if (st != ATLAS_OK) {
        return st;
    }
    atlas_buf existing = ATLAS_BUF_INIT;
    bool exists = false;
    st = read_existing(atlas_buf_cstr(&out->path), &existing, &exists, err);
    if (st != ATLAS_OK) {
        atlas_buf_free(&existing);
        return st;
    }
    if (!exists) {
        out->was_absent = true;
        atlas_buf_free(&existing);
        return ATLAS_OK;
    }
    bool ours = (strstr(atlas_buf_cstr(&existing), ATLAS_UNIT_MARKER) != NULL);
    atlas_buf_free(&existing);
    if (!ours && !force) {
        return atlas_err_set(err, ATLAS_ERR_INTEGRITY,
                             "%s was not written by Atlas; refusing to remove it. Pass --force if "
                             "you are sure.",
                             atlas_buf_cstr(&out->path));
    }
    if (unlink(atlas_buf_cstr(&out->path)) != 0 && errno != ENOENT) {
        return atlas_err_set_errno(err, ATLAS_ERR_CONFIG, errno, "cannot remove %s",
                                   atlas_buf_cstr(&out->path));
    }
    out->removed = true;
    return ATLAS_OK;
}
