/* Atlas - embed a file as a C byte array.
 * Copyright 2026 The Atlas Authors. Licensed under the Apache License 2.0.
 *
 * A9 serves one page from the binary rather than from disk, so the gateway has
 * no filesystem read path at all — which is what makes "no arbitrary filesystem
 * access introduced by the gateway" a property of the code rather than a claim
 * about a directory's permissions.
 *
 * In C for the reason the JSON checker and the fixture generators are: the build
 * depends on no language runtime. `xxd` is not used because it is not
 * guaranteed present; a shell loop is not used because there is no shell in this
 * build.
 *
 * Usage: atlas-embed <symbol> <input> <output>
 */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc != 4) {
        (void)fprintf(stderr, "usage: atlas-embed <symbol> <input> <output>\n");
        return 2;
    }
    const char *symbol = argv[1];
    FILE *in = fopen(argv[2], "rb");
    if (in == NULL) {
        (void)fprintf(stderr, "atlas-embed: cannot read %s\n", argv[2]);
        return 1;
    }
    FILE *out = fopen(argv[3], "wb");
    if (out == NULL) {
        (void)fclose(in);
        (void)fprintf(stderr, "atlas-embed: cannot write %s\n", argv[3]);
        return 1;
    }

    (void)fprintf(out, "/* Generated by atlas-embed from %s. Do not edit. */\n", argv[2]);
    (void)fprintf(out, "#include <stddef.h>\n\n");
    (void)fprintf(out, "const unsigned char %s[] = {\n", symbol);

    size_t n = 0;
    int c;
    while ((c = fgetc(in)) != EOF) {
        (void)fprintf(out, "0x%02x,", (unsigned)(c & 0xff));
        n++;
        if (n % 16u == 0) {
            (void)fputc('\n', out);
        }
    }
    /* A trailing NUL, so the array can also be used as a C string. The length
     * below excludes it: a caller serving bytes must send the file, not the
     * terminator. */
    (void)fprintf(out, "0x00\n};\n");
    (void)fprintf(out, "const size_t %s_len = %zu;\n", symbol, n);

    (void)fclose(in);
    if (fclose(out) != 0) {
        (void)fprintf(stderr, "atlas-embed: cannot finish writing %s\n", argv[3]);
        return 1;
    }
    return 0;
}
